version: "3.9"

services:
  ss14-labeller:
    image: ghcr.io/space-wizards/ss14.labeller:latest
    container_name: ss14-labeller
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      DISCOURSE_CLIENT_API_KEY: ${DISCOURSE_CLIENT_API_KEY}
      DISCOURSE_CLIENT_USERNAME: ${DISCOURSE_CLIENT_USERNAME}
      DISCOURSE_DISCUSSION_CATEGORY: ${DISCOURSE_DISCUSSION_CATEGORY}
      DISCOURSE_CLIENT_URL: ${DISCOURSE_CLIENT_URL}
      ASPNETCORE_URLS: http://+:5000