services:
  ss14-labeller:
    image: ghcr.io/space-wizards/ss14.labeller:latest
    container_name: ss14-labeller
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: http://+:5000
    volumes:
      - ./appsettings.json:/app/appsettings.json
      - ./data:/app/data