name: Build and Publish Docker Image (Linux)

on:
    push:
      tags:
        - 'v*.*.*' # Only triggers on version tags like v1.0.0

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            rid: linux-x64
            runner: ubuntu-latest
          - platform: linux/arm64
            rid: linux-arm64
            runner: ubuntu-24.04-arm
    env:
      IMAGE_NAME: ghcr.io/space-wizards/ss14.labeller
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install NativeAOT Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang zlib1g-dev

      - name: Publish NativeAOT app
        run: |
          dotnet publish -c Release -r ${{ steps.setrid.outputs.rid }} --self-contained true /p:PublishAot=true -o publish

      - name: Prepare release zip
        run: |
          mkdir release
          cp publish/SS14.Labeller release/
          cp README.md LICENCE.txt release/
          cd release && zip -r ../SS14.Labeller-${{ steps.setrid.outputs.rid }}.zip .

      - name: Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          files: SS14.Labeller-${{ steps.setrid.outputs.rid }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-publish:
    runs-on: ubuntu-latest
    needs: build-and-release
    env:
      IMAGE_NAME: ghcr.io/space-wizards/ss14.labeller

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}